// Generated by CoffeeScript 1.8.0

/*
browserify task
---------------
Bundle javascripty things with browserify!

If the watch task is running, this uses watchify instead
of browserify for faster bundling using caching.
 */

(function() {
  var browserify, bundleLogger, gulp, handleErrors, source, watchify;

  browserify = require('browserify');

  watchify = require('watchify');

  bundleLogger = require('../util/bundle_logger');

  gulp = require('gulp');

  handleErrors = require('../util/handle_errors');

  source = require('vinyl-source-stream');

  gulp.task('browserify', function() {
    var bundle, bundler;
    bundler = browserify({
      cache: {},
      packageCache: {},
      fullPaths: true,
      entries: ['./client/src/js/initialize.js'],
      extensions: ['.js', '.hbs'],
      debug: true
    });
    bundle = function() {
      bundleLogger.start();
      return bundler.bundle().on('error', handleErrors).pipe(source('app.js')).pipe(gulp.dest('./client/dist/js')).on('end', bundleLogger.end);
    };
    if (global.isWatching) {
      bundler = watchify(bundler);
      bundler.on('update', bundle);
    }
    return bundle();
  });

}).call(this);
