// Generated by CoffeeScript 1.8.0
(function() {
  var browserSync, gulp;

  browserSync = require('browser-sync');

  gulp = require('gulp');

  gulp.task('browserSync', ['nodemon', 'build'], function() {
    return browserSync({
      proxy: '0.0.0.0:5000',
      port: 5001,
      files: ['client/dist/**']
    });
  });

}).call(this);
