// Generated by CoffeeScript 1.8.0
(function() {
  var browserSync, gulp, nodemon;

  gulp = require('gulp');

  nodemon = require('gulp-nodemon');

  browserSync = require('browser-sync');

  gulp.task('nodemon', ['setEnv'], function() {
    return nodemon({
      script: 'app.js',
      ext: 'js html',
      ignore: ['client/*', 'node_modules/*']
    }).on('restart', function() {
      return setTimeout(function() {
        return browserSync.reload({
          stream: false
        });
      }, 1000);
    });
  });

}).call(this);
