// Generated by CoffeeScript 1.8.0
(function() {
  var gulp, handleErrors;

  gulp = require('gulp');

  handleErrors = require('../util/handle_errors');

  gulp.task('pipeVendorCSS', function() {
    gulp.src('./client/src/js/vendor/bootstrap/dist/**/*').pipe(gulp.dest('./client/dist'));
    return gulp.src('./client/src/js/vendor/bootstrap-material-design/dist/**/*').pipe(gulp.dest('./client/dist'));
  });

}).call(this);
