// Generated by CoffeeScript 1.8.0
(function() {
  var gulp, handleErrors, sass;

  gulp = require('gulp');

  sass = require('gulp-sass');

  handleErrors = require('../util/handle_errors');

  gulp.task('sass', function() {
    return gulp.src('./client/src/css/*.scss').pipe(sass()).pipe(gulp.dest('./client/dist/css'));
  });

}).call(this);
