// Generated by CoffeeScript 1.8.0
(function() {
  var config, fs, gulp, ini, _;

  gulp = require('gulp');

  _ = require('underscore');

  ini = require('ini');

  fs = require('fs');

  if (fs.existsSync('./.env')) {
    config = ini.parse(fs.readFileSync('./.env', 'utf-8'));
    gulp.task('setEnv', function() {
      return _.extend(process.env, config);
    });
  }

}).call(this);
