// Generated by CoffeeScript 1.8.0

/*
Notes:
  - gulp/tasks/browserify.coffee handles coffee recompiling with watchify
  - gulp/tasks/browsersync.coffee watches and reloads compiled files
 */

(function() {
  var gulp;

  gulp = require('gulp');

  gulp.task('watch', ['setWatch', 'browserSync'], function() {
    return gulp.watch('client/src/css/**', ['sass']);
  });

}).call(this);
